"""macro

Revision ID: 170ead0d5b63
Revises: 547963a42886
Create Date: 2017-10-13 11:02:27.454605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170ead0d5b63'
down_revision = '547963a42886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_macros',
    sa.Column('global_macro_id', sa.Integer(), nullable=False),
    sa.Column('macro', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('global_macro_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('server_macros',
    sa.Column('server_macro_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('macro', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('server_macro_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_macros')
    op.drop_table('global_macros')
    # ### end Alembic commands ###
