"""init pillar

Revision ID: 547963a42886
Revises: 157f8e4282f7
Create Date: 2017-08-22 20:36:29.728064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '547963a42886'
down_revision = '157f8e4282f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salt_pillars')
    op.add_column('servers', sa.Column('pillar_content', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'pillar_content')
    op.create_table('salt_pillars',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('priority', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('pillar_content', mysql.JSON(), nullable=True),
    sa.Column('server_instance_id', mysql.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['server_instance_id'], [u'servers.instance_id'], name=u'salt_pillars_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
