"""salt-update

Revision ID: d164fdb4ed73
Revises: fb3cda29f748
Create Date: 2017-10-24 13:57:47.322143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd164fdb4ed73'
down_revision = 'fb3cda29f748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('minion_id', sa.String(length=64), nullable=True),
    sa.Column('pillar', sa.JSON(), nullable=True),
    sa.Column('key_accepted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['servers.instance_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('salt_hosts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salt_hosts',
    sa.Column('instance_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('minion_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('pillar', mysql.JSON(), nullable=True),
    sa.Column('key_accepted', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], [u'servers.instance_id'], name=u'salt_hosts_ibfk_1'),
    sa.PrimaryKeyConstraint('minion_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('salt')
    # ### end Alembic commands ###
