"""salt

Revision ID: fb3cda29f748
Revises: 170ead0d5b63
Create Date: 2017-10-24 10:06:46.466954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb3cda29f748'
down_revision = '170ead0d5b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salt_hosts',
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('minion_id', sa.String(length=64), nullable=False),
    sa.Column('pillar', sa.JSON(), nullable=True),
    sa.Column('key_accepted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['servers.instance_id'], ),
    sa.PrimaryKeyConstraint('minion_id'),
    sa.UniqueConstraint('instance_id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_column(u'servers', 'pillar_content')
    op.drop_column(u'servers', 'minion_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'servers', sa.Column('minion_id', mysql.VARCHAR(length=64), nullable=True))
    op.add_column(u'servers', sa.Column('pillar_content', mysql.JSON(), nullable=True))
    op.drop_table('salt_hosts')
    # ### end Alembic commands ###
